#!/bin/python3
#
# Even fibonacci numbers
#
# Each new term in the Fibonacci sequence is generated by adding the
# previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not
# exceed four million, find the sum of the even-valued terms.
#

MILLION = 4000000

def give_fib():
    """ give_fib: Gives the next fibonacci numbers

        return:
            Integer
    """
    yield 1

    x = y = 1
    while 1:
        temp = y
        y += x
        x = temp
        yield y

def main():
    s = 0
    gen = give_fib()
    while 1:
        n = gen.next()
        if n > MILLION:
            break
        if n%2 == 0:
            s += n

    print(s)

if __name__ == '__main__':
    main()
